export const INTERESTS = [
  { topic: 'Du lịch', label: '✈️ Du lịch' },
  { topic: 'Lịch sử', label: '📜 Lịch sử' },
  { topic: 'Khoa học', label: '🔬 Khoa học' },
  { topic: 'Thiên nhiên', label: '🌿 Thiên nhiên' },
  { topic: 'Ẩm thực', label: '🍳 Ẩm thực' },
  { topic: 'Âm nhạc', label: '🎵 Âm nhạc' },
  { topic: 'Thể thao', label: '⚽ Thể thao' },
  { topic: 'Công nghệ', label: '💻 Công nghệ' },
  { topic: 'Nghệ thuật', label: '🎨 Nghệ thuật' },
  { topic: 'Văn học', label: '📚 Văn học' },
  { topic: 'Điện ảnh', label: '🎬 Điện ảnh' },
  { topic: 'Thời trang', label: '👗 Thời trang' },
  { topic: 'Sức khỏe', label: '🏥 Sức khỏe' },
  { topic: 'Giáo dục', label: '🎓 Giáo dục' },
  { topic: 'Kinh doanh', label: '💼 Kinh doanh' },
  { topic: 'Tài chính', label: '💰 Tài chính' },
  { topic: 'Vũ trụ', label: '🚀 Vũ trụ' },
  { topic: 'Động vật', label: '🐾 Động vật' },
  { topic: 'Môi trường', label: '🌍 Môi trường' },
  { topic: 'Chính trị', label: '🏛️ Chính trị' },
  { topic: 'Tôn giáo', label: '🙏 Tôn giáo' },
  { topic: 'Tâm lý học', label: '🧠 Tâm lý học' },
  { topic: 'Triết học', label: '💭 Triết học' },
  { topic: 'Nhiếp ảnh', label: '📷 Nhiếp ảnh' },
  { topic: 'Trò chơi', label: '🎮 Trò chơi' },
  { topic: 'Làm vườn', label: '🌻 Làm vườn' },
  { topic: 'Xe cộ', label: '🚗 Xe cộ' },
  { topic: 'Kiến trúc', label: '🏗️ Kiến trúc' },
  { topic: 'Pháp luật', label: '⚖️ Pháp luật' },
  { topic: 'Ngôn ngữ', label: '🗣️ Ngôn ngữ' },
  { topic: 'Toán học', label: '➕ Toán học' },
  { topic: 'Địa lý', label: '🗺️ Địa lý' },
  { topic: 'Hóa học', label: '🧪 Hóa học' },
  { topic: 'Vật lý', label: '⚡ Vật lý' },
  { topic: 'Sinh học', label: '🧬 Sinh học' },
  { topic: 'Thiên văn', label: '🔭 Thiên văn' },
  { topic: 'Gia đình', label: '👨‍👩‍👧‍👦 Gia đình' },
  { topic: 'Tình yêu', label: '❤️ Tình yêu' },
  { topic: 'Lễ hội', label: '🏮 Lễ hội' },
  { topic: 'Thủ công', label: '🧶 Thủ công' },
  { topic: 'Yoga', label: '🧘 Yoga' },
  { topic: 'Thiền định', label: '🕯️ Thiền định' },
  { topic: 'Lặn biển', label: '🤿 Lặn biển' },
  { topic: 'Leo núi', label: '🧗 Leo núi' },
  { topic: 'Nông nghiệp', label: '🚜 Nông nghiệp' },
  { topic: 'Hải dương', label: '🌊 Hải dương' },
  { topic: 'Thần thoại', label: '🦄 Thần thoại' },
  { topic: 'Kịch nghệ', label: '🎭 Kịch nghệ' },
  { topic: 'Phong cách sống', label: '✨ Phong cách sống' },
  { topic: 'Thời tiết', label: '🌈 Thời tiết' },
];
