export const ROUTE = {
  HOME: '/',
  TOPIC: '/topic',
  LEARN: '/learn',
  ONION: '/onion',
  GYM: '/gym',
  NEWS: '/news',
  READING: '/reading',
  SPACE: '/solo',
  USER: (username: string) => `/u/${username}`,
  ADMIN: {
    INDEX: '/admin',
    USER_MANAGEMENT: '/admin/users',
    POST_MANAGEMENT: '/admin/posts',
    LISTENING_SESSION_MANAGEMENT: '/admin/listening-session',
    SOLO_SPACE_MANAGEMENT: '/admin/solo-space',
  },
  SETTING: {
    INDEX: '/settings',
    CHANGE_PASSWORD: '/settings/change-password',
    POLICY: '/settings/policy',
    TERMS: '/settings/terms',
    CONTACT: '/settings/contact',
    DELETE_ACCOUNT: '/settings/delete-account',
  },
  PROFILE: `/profile`,
  AUTH: {
    LOGIN: '/login',
    LOGOUT: '/logout',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
  },
};
