export const CHATBOT_PAGES_DATA = [
  {
    pageName: 'Trang chủ',
    pageUrl: 'https://aeiouly.site/',
    description:
      'Trang chủ của nền tảng học tiếng Anh Aeiouly với giới thiệu tổng quan về các tính năng và lộ trình học',
    features: [
      'Giới thiệu platform',
      'Thống kê học viên',
      'Đánh giá từ cộng đồng',
      'Đăng ký tài khoản',
    ],
    keywords: ['trang chủ', 'home', 'aeiouly', 'học tiếng anh', 'nền tảng', 'AI'],
  },
  {
    pageName: 'Luyện nói - Onion',
    pageUrl: 'https://aeiouly.site/onion',
    description:
      'Trang luyện nói tiếng Anh với AI Chat Bot thông minh, thực hành giao tiếp trong các tình huống thực tế',
    features: [
      'AI Chat Bot',
      '8 tình huống thực tế',
      'Phản hồi thời gian thực',
      'Luyện tập cá nhân hóa',
      'Theo dõi tiến độ',
    ],
    keywords: [
      'luyện nói',
      'speaking',
      'AI chat bot',
      'giao tiếp',
      'onion',
      'phát âm',
      'hội thoại',
    ],
  },
  {
    pageName: 'Thảo luận chủ đề - Topic',
    pageUrl: 'https://aeiouly.site/topic',
    description:
      'Thảo luận và trao đổi về các chủ đề tiếng Anh thú vị với cộng đồng, học thông qua chia sẻ ý kiến',
    features: [
      '25+ chủ đề đa dạng',
      'Thảo luận cộng đồng',
      'Chia sẻ bài viết',
      'Giao tiếp thực tế',
    ],
    keywords: ['thảo luận', 'topic', 'discussion', 'cộng đồng', 'chủ đề', 'giao tiếp', 'chia sẻ'],
  },
  {
    pageName: 'Luyện nghe - Gym',
    pageUrl: 'https://aeiouly.site/gym',
    description:
      'Luyện nghe tiếng Anh với bài tập tương tác, video YouTube và công nghệ AI để cải thiện kỹ năng nghe hiểu',
    features: [
      'Bài tập nghe tương tác',
      'Video YouTube',
      'AI đánh giá',
      'Nghe hiểu cá nhân hóa',
      'Các cấp độ khác nhau',
    ],
    keywords: ['luyện nghe', 'listening', 'gym', 'nghe hiểu', 'video', 'bài tập nghe', 'AI'],
  },
  {
    pageName: 'Luyện đọc - Reading',
    pageUrl: 'https://aeiouly.site/reading',
    description:
      'Cải thiện kỹ năng đọc hiểu tiếng Anh với các bài đọc đa dạng và bài tập tương tác',
    features: ['Bài đọc đa dạng', 'Câu hỏi đọc hiểu', 'Mở rộng từ vựng', 'Phân tích văn bản'],
    keywords: ['luyện đọc', 'reading', 'đọc hiểu', 'văn bản', 'từ vựng', 'comprehension'],
  },
  {
    pageName: 'Không gian tự học - Solo Space',
    pageUrl: 'https://aeiouly.site/solo',
    description:
      'Không gian tự học cá nhân với nội dung được tùy chỉnh, âm thanh thư giãn và video nền để tập trung học tập',
    features: [
      'Học tập cá nhân hóa',
      'Âm thanh thư giãn',
      'Video nền tập trung',
      'Môi trường học tập tối ưu',
    ],
    keywords: ['tự học', 'solo', 'space', 'cá nhân hóa', 'tập trung', 'môi trường học'],
  },
  {
    pageName: 'Từ vựng cá nhân - Vocabulary',
    pageUrl: 'https://aeiouly.site/vocabulary',
    description:
      'Quản lý và học từ vựng hiệu quả với flashcard, quiz và hệ thống ôn tập thông minh',
    features: [
      'Flashcard tương tác',
      'Quiz từ vựng',
      'Ôn tập thông minh',
      'Theo dõi tiến độ',
      'Từ vựng cá nhân',
    ],
    keywords: ['từ vựng', 'vocabulary', 'flashcard', 'quiz', 'ôn tập', 'học từ'],
  },
  {
    pageName: 'Đăng nhập',
    pageUrl: 'https://aeiouly.site/login',
    description: 'Trang đăng nhập vào hệ thống Aeiouly để truy cập các tính năng học tiếng Anh',
    features: ['Đăng nhập tài khoản', 'Bảo mật thông tin', 'Quên mật khẩu', 'Ghi nhớ đăng nhập'],
    keywords: ['đăng nhập', 'login', 'tài khoản', 'mật khẩu', 'bảo mật'],
  },
  {
    pageName: 'Đăng ký',
    pageUrl: 'https://aeiouly.site/register',
    description: 'Tạo tài khoản mới để bắt đầu hành trình học tiếng Anh cùng Aeiouly',
    features: ['Tạo tài khoản mới', 'Xác thực email', 'Thiết lập profile', 'Chọn mục tiêu học'],
    keywords: ['đăng ký', 'register', 'tài khoản mới', 'sign up', 'tạo tài khoản'],
  },
  {
    pageName: 'Profile cá nhân',
    pageUrl: 'https://aeiouly.site/profile',
    description: 'Trang quản lý thông tin cá nhân, theo dõi tiến độ học tập và cài đặt tài khoản',
    features: [
      'Thông tin cá nhân',
      'Theo dõi tiến độ',
      'Thống kê học tập',
      'Cài đặt tài khoản',
      'Avatar và theme',
    ],
    keywords: ['profile', 'hồ sơ', 'tiến độ', 'thống kê', 'cài đặt', 'thông tin cá nhân'],
  },
  {
    pageName: 'Cài đặt',
    pageUrl: 'https://aeiouly.site/settings',
    description: 'Trang cài đặt hệ thống bao gồm đổi mật khẩu, chính sách, điều khoản và liên hệ',
    features: [
      'Đổi mật khẩu',
      'Chính sách bảo mật',
      'Điều khoản sử dụng',
      'Liên hệ hỗ trợ',
      'Xóa tài khoản',
    ],
    keywords: ['cài đặt', 'settings', 'mật khẩu', 'bảo mật', 'hỗ trợ', 'chính sách'],
  },
  {
    pageName: 'Tin tức',
    pageUrl: 'https://aeiouly.site/news',
    description: 'Cập nhật tin tức mới nhất về học tiếng Anh, tips học tập và thông báo từ Aeiouly',
    features: ['Tin tức học tiếng Anh', 'Tips học tập', 'Cập nhật tính năng', 'Blog giáo dục'],
    keywords: ['tin tức', 'news', 'blog', 'tips', 'cập nhật', 'thông báo'],
  },
  {
    pageName: 'Quản trị hệ thống',
    pageUrl: 'https://aeiouly.site/admin',
    description:
      'Khu vực dành cho quản trị viên để quản lý người dùng, nội dung và cấu hình hệ thống',
    features: [
      'Quản lý người dùng',
      'Quản lý bài đăng',
      'Quản lý bài test nghe',
      'Quản lý không gian solo',
    ],
    keywords: ['admin', 'quản trị', 'quản lý', 'hệ thống', 'người dùng', 'nội dung'],
  },
];

// Thông tin về các tình huống luyện nói cụ thể
export const ONION_SITUATIONS_DATA = [
  {
    id: 1,
    name: 'Gọi cà phê',
    description: 'Luyện tập đặt đồ uống yêu thích và trò chuyện với nhân viên pha chế',
    difficulty: 'Người mới',
    duration: '3-5 phút',
    category: 'Cuộc sống',
    keywords: ['cà phê', 'coffee', 'đặt hàng', 'giao tiếp hàng ngày'],
  },
  {
    id: 2,
    name: 'Phỏng vấn xin việc',
    description: 'Chuẩn bị cho các câu hỏi phỏng vấn thường gặp và luyện giao tiếp chuyên nghiệp',
    difficulty: 'Nâng cao',
    duration: '10-15 phút',
    category: 'Công việc',
    keywords: ['phỏng vấn', 'interview', 'xin việc', 'chuyên nghiệp'],
  },
  {
    id: 3,
    name: 'Buổi hẹn đầu tiên',
    description: 'Điều hướng sự phấn khích và lo lắng khi tìm hiểu về ai đó đặc biệt',
    difficulty: 'Trung bình',
    duration: '8-12 phút',
    category: 'Xã hội',
    keywords: ['hẹn hò', 'date', 'làm quen', 'giao tiếp xã hội'],
  },
  {
    id: 4,
    name: 'Thuyết trình đại học',
    description: 'Trình bày nghiên cứu hoặc dự án của bạn trước bạn học và giáo sư',
    difficulty: 'Nâng cao',
    duration: '12-20 phút',
    category: 'Học tập',
    keywords: ['thuyết trình', 'presentation', 'đại học', 'học thuật'],
  },
  {
    id: 5,
    name: 'Check-in sân bay',
    description: 'Xử lý thủ tục du lịch, đặt câu hỏi và giải quyết các vấn đề có thể xảy ra',
    difficulty: 'Trung bình',
    duration: '5-8 phút',
    category: 'Du lịch',
    keywords: ['sân bay', 'airport', 'check-in', 'du lịch', 'travel'],
  },
  {
    id: 6,
    name: 'Họp nhóm',
    description: 'Đóng góp ý tưởng, đặt câu hỏi và hợp tác hiệu quả với đồng nghiệp',
    difficulty: 'Trung bình',
    duration: '10-15 phút',
    category: 'Công việc',
    keywords: ['họp nhóm', 'meeting', 'teamwork', 'công việc'],
  },
  {
    id: 7,
    name: 'Mua sắm',
    description: 'Yêu cầu trợ giúp tìm sản phẩm, so sánh hàng hóa và đưa ra quyết định',
    difficulty: 'Người mới',
    duration: '4-6 phút',
    category: 'Cuộc sống',
    keywords: ['mua sắm', 'shopping', 'cửa hàng', 'giao dịch'],
  },
  {
    id: 8,
    name: 'Khám bác sĩ',
    description: 'Thảo luận triệu chứng, hiểu lời khuyên y tế và đặt câu hỏi quan trọng',
    difficulty: 'Trung bình',
    duration: '8-10 phút',
    category: 'Y tế',
    keywords: ['bác sĩ', 'doctor', 'khám bệnh', 'y tế', 'sức khỏe'],
  },
];

// Thông tin về các chủ đề thảo luận
export const TOPIC_CATEGORIES = [
  'AI',
  'Art',
  'Business',
  'Culture',
  'Economy',
  'Education',
  'Environment',
  'Finance',
  'Food',
  'Gaming',
  'Health',
  'History',
  'Lifestyle',
  'Marketing',
  'Movies',
  'Music',
  'Nature',
  'Politics',
  'Programming',
  'Psychology',
  'Science',
  'Space',
  'Sports',
  'Technologies',
  'Travel',
];
