export const interests = [
  { topic: 'Du lịch', display: '✈️ Du lịch' },
  { topic: 'Lịch sử', display: '📜 Lịch sử' },
  { topic: 'Khoa học', display: '🔬 Khoa học' },
  { topic: 'Thiên nhiên', display: '🌿 Thiên nhiên' },
  { topic: 'Ẩm thực', display: '🍳 Ẩm thực' },
  { topic: 'Âm nhạc', display: '🎵 Âm nhạc' },
  { topic: 'Thể thao', display: '⚽ Thể thao' },
  { topic: 'Công nghệ', display: '💻 Công nghệ' },
  { topic: 'Nghệ thuật', display: '🎨 Nghệ thuật' },
  { topic: 'Văn học', display: '📚 Văn học' },
  { topic: 'Điện ảnh', display: '🎬 Điện ảnh' },
  { topic: 'Thời trang', display: '👗 Thời trang' },
  { topic: 'Sức khỏe', display: '🏥 Sức khỏe' },
  { topic: 'Giáo dục', display: '🎓 Giáo dục' },
  { topic: 'Kinh doanh', display: '💼 Kinh doanh' },
  { topic: 'Tài chính', display: '💰 Tài chính' },
  { topic: 'Vũ trụ', display: '🚀 Vũ trụ' },
  { topic: 'Động vật', display: '🐾 Động vật' },
  { topic: 'Môi trường', display: '🌍 Môi trường' },
  { topic: 'Chính trị', display: '🏛️ Chính trị' },
  { topic: 'Tôn giáo', display: '🙏 Tôn giáo' },
  { topic: 'Tâm lý học', display: '🧠 Tâm lý học' },
  { topic: 'Triết học', display: '💭 Triết học' },
  { topic: 'Nhiếp ảnh', display: '📷 Nhiếp ảnh' },
  { topic: 'Trò chơi', display: '🎮 Trò chơi' },
  { topic: 'Làm vườn', display: '🌻 Làm vườn' },
  { topic: 'Xe cộ', display: '🚗 Xe cộ' },
  { topic: 'Kiến trúc', display: '🏗️ Kiến trúc' },
  { topic: 'Pháp luật', display: '⚖️ Pháp luật' },
  { topic: 'Ngôn ngữ', display: '🗣️ Ngôn ngữ' },
  { topic: 'Toán học', display: '➕ Toán học' },
  { topic: 'Địa lý', display: '🗺️ Địa lý' },
  { topic: 'Hóa học', display: '🧪 Hóa học' },
  { topic: 'Vật lý', display: '⚡ Vật lý' },
  { topic: 'Sinh học', display: '🧬 Sinh học' },
  { topic: 'Thiên văn', display: '🔭 Thiên văn' },
  { topic: 'Gia đình', display: '👨‍👩‍👧‍👦 Gia đình' },
  { topic: 'Tình yêu', display: '❤️ Tình yêu' },
  { topic: 'Lễ hội', display: '🏮 Lễ hội' },
  { topic: 'Thủ công', display: '🧶 Thủ công' },
  { topic: 'Yoga', display: '🧘 Yoga' },
  { topic: 'Thiền định', display: '🕯️ Thiền định' },
  { topic: 'Lặn biển', display: '🤿 Lặn biển' },
  { topic: 'Leo núi', display: '🧗 Leo núi' },
  { topic: 'Nông nghiệp', display: '🚜 Nông nghiệp' },
  { topic: 'Hải dương', display: '🌊 Hải dương' },
  { topic: 'Thần thoại', display: '🦄 Thần thoại' },
  { topic: 'Kịch nghệ', display: '🎭 Kịch nghệ' },
  { topic: 'Phong cách sống', display: '✨ Phong cách sống' },
  { topic: 'Thời tiết', display: '🌈 Thời tiết' },
];
